name: Build deb binary package

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Specify version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-deb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: linting
      uses: ./.github/workflows/linterandtests.yml
    - name: build
      uses: ./.github/workflows/pythonbuild.yml
    - name: check
      run: ls -lah && pwd
